---
version: '3'

services:

  django:
    restart: always
    image: ${DOCKER_IMAGE}
    ports:
      - 80:8080
    expose:
      - 8080
    networks:
      - backend
      - frontend
    volumes:
      - ../application:/opt/docker
    depends_on:
      - postgres
    environment:
      # Django
      DJANGO_DEBUG: ${PROJECT_DEBUG}
      DJANGO_PROJECT_NAME: ${PROJECT_NAME}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DJANGO_MEDIA_URL: ${AWS_S3_MEDIA_PATH}
      DJANGO_STATIC_URL: ${AWS_S3_STATIC_PATH}
#      DJANGO_STATICFILES_STORAGE: ${DJANGO_STATICFILES_STORAGE}
#      DJANGO_DEFAULT_FILE_STORAGE: ${DJANGO_DEFAULT_FILE_STORAGE}
      DJANGO_HONEYPOT_FIELD_NAME: ${DJANGO_HONEYPOT_FIELD_NAME}
      # DB
      DJANGO_DB_NAME: ${DB_NAME}
      DJANGO_DB_USER: ${DB_USER}
      DJANGO_DB_PASSWORD: ${DB_PASSWORD}
      DJANGO_DB_HOST: ${DB_HOST}
      DJANGO_DB_PORT: ${DB_PORT}
      # Email
      DJANGO_EMAIL_HOST: ${DJANGO_EMAIL_HOST}
      DJANGO_EMAIL_PORT: ${DJANGO_EMAIL_PORT}
      DJANGO_EMAIL_HOST_USER: ${DJANGO_EMAIL_HOST_USER}
      DJANGO_EMAIL_HOST_PASSWORD: ${DJANGO_EMAIL_HOST_PASSWORD}
      # AWS
      DJANGO_AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      DJANGO_AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DJANGO_AWS_S3_REGION_NAME: ${AWS_S3_REGION}
      DJANGO_AWS_STORAGE_BUCKET_NAME: ${AWS_S3_BUCKET}

  postgres:
    restart: always
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - backend
    volumes:
      - database:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  postgres_backups:
    restart: always
    image: mandelbrew/docker-postgres-s3-backup:latest
    networks:
      - backend
    environment:
      # AWS
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_PATH: ${AWS_S3_BACKUPS_PATH}
      # DB
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  browser-sync:
    restart: always
    image: mandelbrew/browser-sync:1.1
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - frontend
    volumes:
      - ../application:/opt/docker:ro
    command: start --no-open --proxy "django:8080" --files "/opt/docker" --reload-delay "1000"


volumes:
  database: {}

networks:
  backend:
  frontend:
